Mihir Kshirsagar

msk9917

N16144406

# NUMPY

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally

In [1]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

vertical_stack = np.vstack((A, B))

horizontal_stack = np.hstack((A, B))

print("Array A:")
print(A)

print("Array B:")
print(B)

print("Vertically stacked arrays:")
print(vertical_stack)

print("Horizontally stacked arrays:")
print(horizontal_stack)


Array A:
[1 2 3]
Array B:
[4 5 6]
Vertically stacked arrays:
[[1 2 3]
 [4 5 6]]
Horizontally stacked arrays:
[1 2 3 4 5 6]


2. Find common elements between A and B

In [2]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

common_elements = np.intersect1d(A, B)

print("Common elements between A and B:")
print(common_elements)


Common elements between A and B:
[3 4 5]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10

In [3]:
A = np.array([2, 6, 8, 4, 10, 12, 7, 9])

min_range = 5
max_range = 10

filtered_array = A[(A >= min_range) & (A <= max_range)]

print("Numbers within the range [{}, {}]: ".format(min_range, max_range))
print(filtered_array)


Numbers within the range [5, 10]: 
[ 6  8 10  7  9]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

filtered_rows = iris_2d[condition]

print("Filtered rows of iris_2d:")
print(filtered_rows)


Filtered rows of iris_2d:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# PANDAS

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0) df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [5]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_data = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

filtered_data.reset_index(drop=True, inplace=True)

print(filtered_data)


  Manufacturer    Model     Type
0        Acura  Integra    Small
1     Chrysler  LeBaron  Compact
2        Honda  Prelude   Sporty
3      Mercury   Cougar  Midsize
4       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean. df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

print(df)


   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

3. How to get the rows of a dataframe with row sum > 100?
df=pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [7]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

row_sums = df.sum(axis=1)

result = df[row_sums > 100]

print(result)


     0   1   2   3
3   28  22  15  38
6   20  31  37  32
8   35  17  29  20
13  11  34  28  39
14  30  13  29  32
